# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7509d7ad74e5f49e3b275265443d956639c192251e7e77a80b1218a673753fb39cf573bf90c52f512b709770a33765b018e72facae8c9bf4a0a448a20f7a46

test:
  secret_key_base: 3e7a37ca8d9c941acb0e78e4b5953e9b39bb5d1cdc0403c384f1cfcf354022b6d350c5d2939b337b9e99aa34cce7317fff73c36bfc84cb46118f9c9a13589d6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
